version: "3.6"
services:
  fishroom:
    image: fishroom:latest
    environment:
      - FISHROOM_MODE=fishroom
    depends_on:
      - redis
    logging:
      options:
        max-size: "10M"
  irc:
    image: fishroom:latest
    environment:
      - FISHROOM_MODE=IRC
    depends_on:
      - fishroom
    logging:
      options:
        max-size: "10M"
  redis:
    image: redis:4.0-alpine
    logging:
      options:
        max-size: "10M"

